library(xlsx)
library(ggplot2)
setwd("C:\\Documentos\\github\\TFM\\images")
vals <- read.xlsx("res.xlsx", 0, sheetName = "Val")
res <- vals
res <- subset(res, Zone == 'gray')
res <- subset(res, Meas == 'FA')
res1 <- subset(res, Time == 'X1')
res2 <- subset(res, Time == 'X2')
pdf("res.pdf")
g <- ggplot() + geom_point(data = res1, aes(x = Animal, y = Val), colour = "red")
g <- g + geom_point(data = res2, aes(x = Animal, y = Val), colour = "blue")
g <- g + ggtitle("FA gray matter Red = Control Blue = Lesion") + xlab("Animal") + ylab("FA")
g <- g + theme_bw()
print(g)
res <- vals
res <- subset(res, Zone == 'gray')
res <- subset(res, Meas == 'MD')
res1 <- subset(res, Time == 'X1')
res2 <- subset(res, Time == 'X2')
g <- ggplot() + geom_point(data = res1, aes(x = Animal, y = Val), colour = "red")
g <- g + geom_point(data = res2, aes(x = Animal, y = Val), colour = "blue")
g <- g + ggtitle("MD gray matter Red = Control Blue = Lesion") + xlab("Animal") + ylab("MD")
g <- g + theme_bw()
print(g)
res <- vals
res <- subset(res, Zone == 'white')
res <- subset(res, Meas == 'FA')
res1 <- subset(res, Time == 'X1')
res2 <- subset(res, Time == 'X2')
g <- ggplot() + geom_point(data = res1, aes(x = Animal, y = Val), colour = "red")
g <- g + geom_point(data = res2, aes(x = Animal, y = Val), colour = "blue")
g <- g + ggtitle("FA white matter Red = Control Blue = Lesion") + xlab("Animal") + ylab("FA")
g <- g + theme_bw()
print(g)
res <- vals
res <- subset(res, Zone == 'white')
res <- subset(res, Meas == 'MD')
res1 <- subset(res, Time == 'X1')
res2 <- subset(res, Time == 'X2')
g <- ggplot() + geom_point(data = res1, aes(x = Animal, y = Val), colour = "red")
g <- g + geom_point(data = res2, aes(x = Animal, y = Val), colour = "blue")
g <- g + ggtitle("MD white matter Red = Control Blue = Lesion") + xlab("Animal") + ylab("MD")
g <- g + theme_bw()
print(g)
dev.off()




